version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgresql-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" 
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-echo-app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}  
      DB_PORT: ${DB_PORT}  
      DB_NAME: ${DB_NAME}  
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - db 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
